# Generated by Django 5.0.9 on 2025-04-15 17:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonelYonSis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CreationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Telefon numarası 5xxxxxxxxx formatında olmalıdır.', regex='^5\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='TCKimlikNo',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
