# Generated by Django 5.0.9 on 2025-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonelYonSis', '0002_user_creationtime_user_email_user_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
