# Generated by Django 5.0.9 on 2025-09-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonelYonSis', '0005_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='session_key',
        ),
    ]
