# Generated by Django 5.0.9 on 2025-11-17 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_duyuru_permission(apps, schema_editor):
    Permission = apps.get_model('PersonelYonSis', 'Permission')
    Permission.objects.get_or_create(PermissionName="Genel Duyuru Ekleyebilir")


def remove_duyuru_permission(apps, schema_editor):
    Permission = apps.get_model('PersonelYonSis', 'Permission')
    Permission.objects.filter(PermissionName="Genel Duyuru Ekleyebilir").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('PersonelYonSis', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uygulama', models.CharField(help_text='Örn: mercis657, ik_core, genel', max_length=100)),
                ('duyuru_metni', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duyurular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.RunPython(create_duyuru_permission, remove_duyuru_permission),
    ]
