# Generated by Django 5.0.9 on 2025-12-03 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonelYonSis', '0008_duyuru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istek', models.TextField()),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tamamlanma_durumu', models.CharField(choices=[('Beklemede', 'Beklemede'), ('İşlemde', 'İşlemde'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Beklemede', max_length=20)),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('talep_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istekler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstek',
                'verbose_name_plural': 'İstekler',
                'ordering': ['-talep_tarihi'],
            },
        ),
    ]
