# Generated by Django 5.0.9 on 2024-10-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesai_Tanimlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saat', models.CharField(max_length=11)),
                ('GunduzMesaisi', models.BooleanField(default=False)),
                ('AksamMesaisi', models.BooleanField(default=False)),
                ('GeceMesaisi', models.BooleanField(default=False)),
                ('IseGeldi', models.BooleanField(default=False)),
                ('SonrakiGuneSarkiyor', models.BooleanField(default=False)),
                ('AraDinlenme', models.DurationField(blank=True, null=True)),
                ('GecerliMesai', models.BooleanField(default=True)),
                ('CKYS_BTF_Karsiligi', models.CharField(blank=True, max_length=100, null=True)),
                ('Sure', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mesai',
            name='MesaiData',
        ),
        migrations.AddField(
            model_name='mesai',
            name='MesaiTanim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mercis657.mesai_tanimlari'),
        ),
    ]
