# Generated by Django 5.0.9 on 2025-06-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0005_alter_personel_teskilat'),
        ('mercis657', '0002_mesai_tanimlari_remove_mesai_mesaidata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('BirimID', models.AutoField(primary_key=True, serialize=False)),
                ('BirimAdi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personel',
            name='BirthDate',
        ),
        migrations.CreateModel(
            name='PersonelListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveIntegerField()),
                ('ay', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_listeleri', to='mercis657.birim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personel Listesi',
                'verbose_name_plural': 'Personel Listeleri',
                'unique_together': {('birim', 'yil', 'ay')},
            },
        ),
        migrations.CreateModel(
            name='PersonelListesiKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='mercis657.personellistesi')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.personel')),
            ],
            options={
                'verbose_name': 'Personel Listesi Kayıt',
                'verbose_name_plural': 'Personel Listesi Kayıtları',
                'unique_together': {('liste', 'personel')},
            },
        ),
        migrations.CreateModel(
            name='UserBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_kullanicilari', to='mercis657.birim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_birimleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Birim Yetkisi',
                'verbose_name_plural': 'Kullanıcı Birim Yetkileri',
                'unique_together': {('user', 'birim')},
            },
        ),
    ]
