# Generated by Django 5.0.9 on 2025-06-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0003_birim_remove_personel_birthdate_personellistesi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MudurYardimcisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UstBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='birim',
            name='Kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercis657.kurum'),
        ),
        migrations.AddField(
            model_name='birim',
            name='MudurYrd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercis657.muduryardimcisi'),
        ),
        migrations.AddField(
            model_name='birim',
            name='UstBirim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercis657.ustbirim'),
        ),
    ]
