# Generated by Django 5.0.9 on 2025-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0005_alter_personellistesikayit_personel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
                ('kod', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='personel',
            name='PersonelTCKN',
            field=models.BigIntegerField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personel',
            name='PersonelID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
