# Generated by Django 5.0.9 on 2025-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0005_alter_personellistesikayit_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='PersonelTCKN',
            field=models.BigIntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='PersonelID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
