# Generated by Django 5.0.9 on 2025-06-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0006_izin_personel_personeltckn_alter_personel_personelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurum',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='muduryardimcisi',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ustbirim',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
