# Generated by Django 5.1.6 on 2025-09-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0008_rename_muduryardimcisi_idareci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='kod',
            field=models.CharField(max_length=20),
        ),
    ]
