# Generated by Django 5.0.9 on 2025-09-06 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0009_alter_izin_kod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai',
            name='Degisiklik',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mesai',
            name='Izin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_mesai_izin', to='mercis657.izin'),
        ),
        migrations.AddField(
            model_name='mesai',
            name='OnayDurumu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesai',
            name='OnayTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesai',
            name='Onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_mesai_onaylayan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesai',
            name='SilindiMi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='MesaiTanim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_mesai_tanimlari', to='mercis657.mesai_tanimlari'),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='Personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_mesai_personel', to='mercis657.personel'),
        ),
    ]
