# Generated by Django 5.0.9 on 2025-09-06 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0010_mesai_degisiklik_mesai_izin_mesai_onaydurumu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesai',
            name='OnayDurumu',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MesaiYedek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SilindiMi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Izin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_mesaiyedek_izin', to='mercis657.izin')),
                ('MesaiTanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_mesaiyedek_tanim', to='mercis657.mesai_tanimlari')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_mesaiyedek_ekleyen', to=settings.AUTH_USER_MODEL)),
                ('mesai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yedekler', to='mercis657.mesai')),
            ],
            options={
                'verbose_name': 'Mesai Yedeği',
                'verbose_name_plural': 'Mesai Yedekleri',
            },
        ),
    ]
