# Generated by Django 5.0.9 on 2025-09-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0011_alter_mesai_onaydurumu_mesaiyedek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesai',
            name='SilindiMi',
        ),
        migrations.RemoveField(
            model_name='mesaiyedek',
            name='SilindiMi',
        ),
    ]
