# Generated by Django 5.0.9 on 2025-09-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0012_remove_mesai_silindimi_remove_mesaiyedek_silindimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesai',
            name='Degisiklik',
            field=models.BooleanField(default=False),
        ),
    ]
