# Generated by Django 5.0.9 on 2025-09-07 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0013_alter_mesai_degisiklik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResmiTatil',
            fields=[
                ('TatilID', models.AutoField(primary_key=True, serialize=False)),
                ('TatilTarihi', models.DateField()),
                ('Aciklama', models.CharField(max_length=200)),
                ('TatilTipi', models.CharField(choices=[('TAM', 'Tam Gün'), ('YARIM', 'Yarım Gün')], default='TAM', max_length=10)),
                ('BayramMi', models.BooleanField(default=False)),
                ('ArefeMi', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['TatilTarihi'],
            },
        ),
        migrations.AddField(
            model_name='personellistesikayit',
            name='radyasyon_calisani',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MazeretKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('gunluk_azaltim_saat', models.DecimalField(decimal_places=2, help_text='Günlük azaltım saati (örn: 3.00, 1.50)', max_digits=4)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazeret_kayitlari', to='mercis657.personel')),
            ],
            options={
                'verbose_name': 'Mazeret Kaydı',
                'verbose_name_plural': 'Mazeret Kayıtları',
            },
        ),
    ]
