# Generated by Django 5.0.9 on 2025-09-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0014_resmitatil_personellistesikayit_radyasyon_calisani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personellistesi',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
