# Generated by Django 5.0.9 on 2025-09-10 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0015_personellistesi_aciklama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('BildirimID', models.AutoField(primary_key=True, serialize=False)),
                ('DonemBaslangic', models.DateField()),
                ('NormalFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('BayramFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('RiskliNormalFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('RiskliBayramFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('NormalIcap', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('BayramIcap', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('MesaiDetay', models.JSONField(blank=True, null=True)),
                ('IcapDetay', models.JSONField(blank=True, null=True)),
                ('OlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('OnayTarihi', models.DateTimeField(null=True)),
                ('OnayDurumu', models.IntegerField(default=0)),
                ('SilindiMi', models.BooleanField(default=False)),
                ('MutemetKilit', models.BooleanField(default=False)),
                ('MutemetKilitTime', models.DateTimeField(blank=True, null=True)),
                ('MutemetKilitUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_mutemet_kilit_kullanicilar', to=settings.AUTH_USER_MODEL)),
                ('OlusturanKullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_olusturan_bildirimler', to=settings.AUTH_USER_MODEL)),
                ('OnaylayanKullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_onaylayan_bildirimler', to=settings.AUTH_USER_MODEL)),
                ('PersonelListesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_bildirimler', to='mercis657.personellistesi')),
            ],
            options={
                'unique_together': {('PersonelListesi', 'DonemBaslangic')},
            },
        ),
    ]
