# Generated by Django 5.1.6 on 2025-09-11 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0016_bildirim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bildirim',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='Personel',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_bildirimler', to='mercis657.personel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bildirim',
            unique_together={('Personel', 'DonemBaslangic')},
        ),
    ]
