# Generated by Django 5.0.9 on 2025-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0017_alter_bildirim_unique_together_bildirim_personel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai_tanimlari',
            name='Renk',
            field=models.CharField(default='#000000', help_text='Çizelgede görünecek yazı rengi', max_length=7),
        ),
    ]
