# Generated by Django 5.0.9 on 2025-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0018_mesai_tanimlari_renk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesai_tanimlari',
            name='Renk',
            field=models.CharField(help_text='Çizelgede görünecek yazı rengi', max_length=7, null=True),
        ),
    ]
