# Generated by Django 5.0.9 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0019_alter_mesai_tanimlari_renk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesai_tanimlari',
            name='Sure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mesai süresi saat cinsinden (örn: 9.5)', max_digits=4, null=True),
        ),
    ]
