# Generated by Django 5.0.9 on 2025-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0020_alter_mesai_tanimlari_sure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesai_tanimlari',
            name='AraDinlenme',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mesai ara dinlenmesi saat cinsinden (örn: 1.5)', max_digits=4, null=True),
        ),
    ]
