# Generated by Django 5.1.6 on 2025-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0021_alter_mesai_tanimlari_aradinlenme'),
    ]

    operations = [
        migrations.AddField(
            model_name='birim',
            name='BayramNobetKodu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birim',
            name='NormalNobetKodu',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='birim',
            name='RiskliBayramNobetKodu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birim',
            name='RiskliNormalNobetKodu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesai_tanimlari',
            name='Renk',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
