# Generated by Django 5.0.9 on 2025-09-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0022_birim_bayramnobetkodu_birim_normalnobetkodu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='PersonelSurname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
