# Generated by Django 5.0.9 on 2025-09-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0023_personel_personelsurname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai',
            name='SistemdekiIzin',
            field=models.BooleanField(default=False),
        ),
    ]
