# Generated by Django 5.0.9 on 2025-09-24 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0024_mesai_sistemdekiizin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai',
            name='MesaiNotu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesai',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_mesai_ekleyen', to=settings.AUTH_USER_MODEL),
        ),
    ]
