# Generated by Django 5.0.9 on 2025-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0025_mesai_mesainotu_mesai_created_at_mesai_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='personellistesikayit',
            name='sira_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
