# Generated by Django 5.0.9 on 2025-10-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0026_personellistesikayit_sira_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='YarimZamanliCalisma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('haftalik_plan', models.JSONField()),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarim_zamanli_donemler', to='mercis657.personel')),
            ],
        ),
    ]
