# Generated by Django 5.1.6 on 2025-10-02 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0027_yarimzamanlicalisma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StopKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StopBaslangic', models.DateTimeField()),
                ('StopBitis', models.DateTimeField()),
                ('Sure', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_stoplar', to='mercis657.mesai')),
            ],
        ),
    ]
