# Generated by Django 5.1.6 on 2025-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0028_stopkaydi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopkaydi',
            name='StopBaslangic',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stopkaydi',
            name='StopBitis',
            field=models.TimeField(),
        ),
    ]
