# Generated by Django 5.0.9 on 2025-10-17 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0029_alter_stopkaydi_stopbaslangic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IlkListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Veriler', models.JSONField(blank=True, null=True)),
                ('OlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('OnayTarihi', models.DateTimeField(blank=True, null=True)),
                ('OnayDurumu', models.BooleanField(default=False)),
                ('OlusturanKullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_olusturan_ilk_liste', to=settings.AUTH_USER_MODEL)),
                ('OnaylayanKullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercis657_onaylayan_ilk_liste', to=settings.AUTH_USER_MODEL)),
                ('PersonelListesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_ilk_liste', to='mercis657.personellistesi')),
            ],
            options={
                'verbose_name': 'İlk Liste Bildirimi',
                'verbose_name_plural': 'İlk Liste Bildirimleri',
                'ordering': ['-OlusturmaTarihi'],
            },
        ),
    ]
