# Generated by Django 5.0.9 on 2025-10-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0031_sabitmesai_personellistesikayit_sabit_mesai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabitmesai',
            name='kod',
        ),
    ]
