# Generated by Django 5.0.9 on 2025-10-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0032_remove_sabitmesai_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birim',
            name='BirimAdi',
            field=models.CharField(max_length=100),
        ),
    ]
