# Generated by Django 5.0.9 on 2025-10-22 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0033_alter_birim_birimadi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMesaiFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favori_kullanicilar', to='mercis657.mesai_tanimlari')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favori_mesaileri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori Mesai',
                'verbose_name_plural': 'Favori Mesailer',
                'unique_together': {('user', 'mesai')},
            },
        ),
    ]
