# Generated by Django 5.0.9 on 2025-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0034_usermesaifavori'),
    ]

    operations = [
        migrations.AddField(
            model_name='izin',
            name='fm_karsiligi',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
