# Generated by Django 5.0.9 on 2025-10-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0035_izin_fm_karsiligi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='ad',
            field=models.CharField(max_length=100),
        ),
    ]
