# Generated by Django 5.0.9 on 2025-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0036_alter_izin_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopkaydi',
            name='Aciklama',
            field=models.TextField(blank=True),
        ),
    ]
