# Generated by Django 5.0.9 on 2025-10-31 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0037_stopkaydi_aciklama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mesai',
            constraint=models.UniqueConstraint(fields=('Personel', 'MesaiDate'), name='unique_personel_mesaidate'),
        ),
    ]
