# Generated by Django 5.1.6 on 2025-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0038_mesai_unique_personel_mesaidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='birim',
            name='Pasif',
            field=models.BooleanField(default=False),
        ),
    ]
