# Generated by Django 5.0.9 on 2025-12-04 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0039_birim_pasif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='birim',
            name='Bina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercis657.bina'),
        ),
        migrations.CreateModel(
            name='MesaiKontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrol', models.BooleanField(default=False)),
                ('kontrol_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kontrol_yapan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesai_kontrolleri', to='mercis657.mesai')),
            ],
            options={
                'verbose_name': 'Mesai Kontrol',
                'verbose_name_plural': 'Mesai Kontrolleri',
                'unique_together': {('mesai',)},
            },
        ),
    ]
