# Generated by Django 5.0.9 on 2026-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0040_bina_birim_bina_mesaikontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='birim',
            name='BayramGeceNobetKodu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birim',
            name='NormalGeceNobetKodu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birim',
            name='RiskliBayramGeceNobetKodu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birim',
            name='RiskliNormalGeceNobetKodu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
