# Generated by Django 5.0.9 on 2026-01-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0041_birim_bayramgecenobetkodu_birim_normalgecenobetkodu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai_tanimlari',
            name='GeceCalismaSure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='20:00–08:00 arası gece çalışma süresi saat cinsinden (örn: 9.5)', max_digits=4, null=True),
        ),
    ]
