# Generated by Django 5.0.9 on 2026-01-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0042_mesai_tanimlari_gececalismasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='GeceBayramFazlaMesai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='GeceNormalFazlaMesai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='GeceRiskliBayramFazlaMesai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='GeceRiskliNormalFazlaMesai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
