# Generated by Django 5.0.9 on 2026-01-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0043_bildirim_gecebayramfazlamesai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personellistesikayit',
            name='is_gunduz_personeli',
            field=models.BooleanField(default=True, help_text='True: Gündüz Personeli, False: Nöbetli Çalışan'),
        ),
    ]
