# Generated by Django 5.0.9 on 2026-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0044_personellistesikayit_is_gunduz_personeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai',
            name='Icap',
            field=models.BooleanField(default=False),
        ),
    ]
