# Generated by Django 5.0.9 on 2026-02-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0045_mesai_icap'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai',
            name='riskli_calisma',
            field=models.CharField(blank=True, choices=[('full', 'Tam Riskli'), ('nobet', 'Nöbet Riskli')], default=None, max_length=10, null=True),
        ),
    ]
