# Generated by Django 5.0.9 on 2026-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0046_mesai_riskli_calisma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopkaydi',
            name='Sure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
