# Generated by Django 5.0.9 on 2026-05-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercis657', '0047_alter_stopkaydi_sure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EkMesai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslangic', models.TimeField()),
                ('Bitis', models.TimeField()),
                ('Sure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Aciklama', models.TextField(blank=True)),
                ('Riskli', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercis657_ek_mesailer', to='mercis657.mesai')),
            ],
        ),
    ]
