# Generated by Django 5.0.9 on 2025-04-07 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('HizmetID', models.AutoField(primary_key=True, serialize=False)),
                ('HizmetName', models.CharField(max_length=100, unique=True)),
                ('HizmetTipi', models.CharField(choices=[('Standart', 'Standart'), ('Nöbet', 'Nöbet'), ('İcap', 'İcap')], max_length=10)),
                ('HizmetSuresiHaftaIci', models.IntegerField(default=480, help_text='Hafta içi hizmet süresi (dakika)')),
                ('HizmetSuresiHaftaSonu', models.IntegerField(blank=True, help_text='Hafta sonu hizmet süresi (dakika)', null=True)),
                ('MaxHekimSayisi', models.IntegerField(default=1, help_text='Aynı gün için maksimum hekim sayısı')),
                ('NobetErtesiIzinli', models.BooleanField(default=False, help_text='Nöbet ertesi izinli mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('IzinID', models.AutoField(primary_key=True, serialize=False)),
                ('IzinTipi', models.CharField(choices=[('Yıllık İzin', 'Yıllık İzin'), ('Nöbet İzni', 'Nöbet İzni'), ('Sendika İzni', 'Sendika İzni'), ('İdari İzin', 'İdari İzin'), ('Mazeret İzni', 'Mazeret İzni')], max_length=50)),
                ('IzinRenk', models.CharField(default='bg-warning', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('PersonelID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('PersonelTitle', models.CharField(max_length=50)),
                ('PersonelBranch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResmiTatil',
            fields=[
                ('TatilID', models.AutoField(primary_key=True, serialize=False)),
                ('TatilTarihi', models.DateField()),
                ('Aciklama', models.CharField(max_length=200)),
                ('TatilTipi', models.CharField(choices=[('TAM', 'Tam Gün'), ('YARIM', 'Yarım Gün')], default='TAM', max_length=10)),
            ],
            options={
                'ordering': ['TatilTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('BirimID', models.AutoField(primary_key=True, serialize=False)),
                ('BirimAdi', models.CharField(max_length=100, unique=True)),
                ('DigerHizmetler', models.ManyToManyField(related_name='diger_birim_hizmetleri', to='hekim_cizelge.hizmet')),
                ('VarsayilanHizmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varsayilan_birim_hizmetleri', to='hekim_cizelge.hizmet')),
            ],
        ),
        migrations.CreateModel(
            name='Mesai',
            fields=[
                ('MesaiID', models.AutoField(primary_key=True, serialize=False)),
                ('MesaiDate', models.DateField()),
                ('OnayDurumu', models.IntegerField(default=0)),
                ('OnayTarihi', models.DateTimeField(blank=True, null=True)),
                ('Degisiklik', models.BooleanField(default=True)),
                ('SilindiMi', models.BooleanField(default=False)),
                ('Hizmetler', models.ManyToManyField(blank=True, related_name='mesai_hizmetleri', to='hekim_cizelge.hizmet')),
                ('Izin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hekim_cizelge.izin')),
                ('Onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.personel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonelBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.birim')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.personel')),
            ],
        ),
        migrations.AddField(
            model_name='personel',
            name='birim',
            field=models.ManyToManyField(through='hekim_cizelge.PersonelBirim', to='hekim_cizelge.birim'),
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('BildirimID', models.AutoField(primary_key=True, serialize=False)),
                ('DonemBaslangic', models.DateField()),
                ('NormalFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('BayramFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('RiskliNormalFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('RiskliBayramFazlaMesai', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('NormalIcap', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('BayramIcap', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('MesaiDetay', models.JSONField(blank=True, null=True)),
                ('IcapDetay', models.JSONField(blank=True, null=True)),
                ('OlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('OnayTarihi', models.DateTimeField(null=True)),
                ('OnayDurumu', models.IntegerField(default=0)),
                ('SilindiMi', models.BooleanField(default=False)),
                ('MutemetKilit', models.BooleanField(default=False)),
                ('MutemetKilitTime', models.DateTimeField(blank=True, null=True)),
                ('MutemetKilitUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutemet_kilit_kullanicilar', to=settings.AUTH_USER_MODEL)),
                ('OlusturanKullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturan_bildirimler', to=settings.AUTH_USER_MODEL)),
                ('OnaylayanKullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylayan_bildirimler', to=settings.AUTH_USER_MODEL)),
                ('PersonelBirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.personelbirim')),
            ],
            options={
                'unique_together': {('PersonelBirim', 'DonemBaslangic')},
            },
        ),
        migrations.CreateModel(
            name='UserBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkili_kullanicilar', to='hekim_cizelge.birim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkili_birimler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'birim')},
            },
        ),
    ]
