# Generated by Django 5.1.6 on 2025-03-17 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('HizmetID', models.AutoField(primary_key=True, serialize=False)),
                ('HizmetName', models.CharField(max_length=100, unique=True)),
                ('HizmetTipi', models.CharField(choices=[('Standart', 'Standart'), ('Nöbet', 'Nöbet'), ('İcap', 'İcap')], max_length=10)),
                ('HizmetSuresiHaftaIci', models.IntegerField(default=480, help_text='Hafta içi hizmet süresi (dakika)')),
                ('HizmetSuresiHaftaSonu', models.IntegerField(blank=True, help_text='Hafta sonu hizmet süresi (dakika)', null=True)),
                ('MaxHekimSayisi', models.IntegerField(default=1, help_text='Aynı gün için maksimum hekim sayısı')),
                ('NobetErtesiIzinli', models.BooleanField(default=False, help_text='Nöbet ertesi izinli mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('PersonelID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonelName', models.CharField(max_length=100)),
                ('PersonelTitle', models.CharField(max_length=50)),
                ('PersonelBranch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('BirimID', models.AutoField(primary_key=True, serialize=False)),
                ('BirimAdi', models.CharField(max_length=100, unique=True)),
                ('DigerHizmetler', models.ManyToManyField(related_name='diger_birim_hizmetleri', to='hekim_cizelge.hizmet')),
                ('VarsayilanHizmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varsayilan_birim_hizmetleri', to='hekim_cizelge.hizmet')),
            ],
        ),
        migrations.CreateModel(
            name='Mesai',
            fields=[
                ('MesaiID', models.AutoField(primary_key=True, serialize=False)),
                ('MesaiDate', models.DateField()),
                ('OnayDurumu', models.IntegerField(default=0)),
                ('OnayTarihi', models.DateTimeField(blank=True, null=True)),
                ('Degisiklik', models.BooleanField(default=True)),
                ('Hizmetler', models.ManyToManyField(related_name='mesai_hizmetleri', to='hekim_cizelge.hizmet')),
                ('Onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.personel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonelBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.birim')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.personel')),
            ],
        ),
        migrations.AddField(
            model_name='personel',
            name='birim',
            field=models.ManyToManyField(through='hekim_cizelge.PersonelBirim', to='hekim_cizelge.birim'),
        ),
        migrations.CreateModel(
            name='UserBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkili_kullanicilar', to='hekim_cizelge.birim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkili_birimler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'birim')},
            },
        ),
    ]
