# Generated by Django 5.0.9 on 2024-11-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('HizmetID', models.AutoField(primary_key=True, serialize=False)),
                ('HizmetName', models.CharField(max_length=100, unique=True)),
                ('HizmetTipi', models.CharField(choices=[('Standart', 'Standart'), ('Nöbet', 'Nöbet'), ('İcap', 'İcap')], max_length=10)),
                ('HizmetSuresi', models.DurationField(help_text="Hizmet süresi, örn: 8 saat için '8:00:00'")),
            ],
        ),
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('BirimID', models.AutoField(primary_key=True, serialize=False)),
                ('BirimAdi', models.CharField(max_length=100, unique=True)),
                ('DigerHizmetler', models.ManyToManyField(related_name='diger_hizmet_birimleri', to='hekim_cizelge.hizmet')),
                ('VarsayilanHizmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varsayilan_hizmet_birimleri', to='hekim_cizelge.hizmet')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('PersonelID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonelName', models.CharField(max_length=100)),
                ('PersonelTitle', models.CharField(max_length=50)),
                ('PersonelBranch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hekim_cizelge.birim')),
            ],
        ),
        migrations.CreateModel(
            name='Mesai',
            fields=[
                ('MesaiID', models.AutoField(primary_key=True, serialize=False)),
                ('MesaiDate', models.DateField()),
                ('Hizmetler', models.ManyToManyField(related_name='mesai_hizmetleri', to='hekim_cizelge.hizmet')),
                ('Personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.personel')),
            ],
        ),
    ]
