# Generated by Django 5.1.6 on 2025-03-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bildirim',
            unique_together={('PersonelBirim', 'DonemBaslangic')},
        ),
        migrations.RemoveField(
            model_name='bildirim',
            name='BildirimTipi',
        ),
    ]
