# Generated by Django 5.0.9 on 2025-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmet',
            name='VarsayilanHizmetleSunulur',
            field=models.BooleanField(default=True, help_text='Bu hizmet varsayılan hizmetle birlikte sunulabilir mi?'),
        ),
    ]
