# Generated by Django 5.0.9 on 2024-11-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='PersonelBirimID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel', to='hekim_cizelge.birim'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='PersonelBranch',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
