# Generated by Django 5.0.3 on 2024-12-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0002_personel_personelbirimid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personel',
            name='PersonelBirimID',
        ),
        migrations.CreateModel(
            name='PersonelBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.birim')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hekim_cizelge.personel')),
            ],
        ),
        migrations.AddField(
            model_name='personel',
            name='birim',
            field=models.ManyToManyField(through='hekim_cizelge.PersonelBirim', to='hekim_cizelge.birim'),
        ),
    ]
