# Generated by Django 5.0.9 on 2025-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0002_hizmet_varsayilanhizmetlesunulur'),
    ]

    operations = [
        migrations.AddField(
            model_name='izin',
            name='MesaidenDus',
            field=models.BooleanField(default=False, help_text='Bu izin tipi çalışma süresinden düşülür mü?'),
        ),
    ]
