# Generated by Django 5.0.9 on 2025-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0003_izin_mesaidendus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='MesaidenDus',
            field=models.BooleanField(default=True, help_text='Bu izin tipi çalışma süresinden düşülür mü?'),
        ),
    ]
