# Generated by Django 5.0.9 on 2024-12-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0004_userbirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birim',
            name='DigerHizmetler',
            field=models.ManyToManyField(related_name='diger_birim_hizmetleri', to='hekim_cizelge.hizmet'),
        ),
        migrations.AlterField(
            model_name='birim',
            name='VarsayilanHizmet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varsayilan_birim_hizmetleri', to='hekim_cizelge.hizmet'),
        ),
    ]
