# Generated by Django 5.0.9 on 2025-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0005_resmitatil_arefemi_resmitatil_bayramadi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai',
            name='TaslakHizmetler',
            field=models.ManyToManyField(blank=True, related_name='taslak_hizmetler', to='hekim_cizelge.hizmet'),
        ),
    ]
