# Generated by Django 5.1.6 on 2025-03-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0006_mesaionay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesai',
            name='Degisiklik',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mesai',
            name='OnayDurumu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesai',
            name='OnayTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesai',
            name='Onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MesaiOnay',
        ),
    ]
