# Generated by Django 5.0.9 on 2025-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0006_mesai_taslakhizmetler'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='TcKimlikNo',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
