# Generated by Django 5.0.9 on 2025-06-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hekim_cizelge', '0007_personel_tckimlikno'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
