# Generated by Django 5.1.6 on 2026-02-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cihaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapi_adi', models.CharField(max_length=100, verbose_name='Kapı Adı')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP Adresi')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='Port')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
            },
        ),
        migrations.CreateModel(
            name='CihazKullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(verbose_name='UID')),
                ('user_id', models.CharField(max_length=50, verbose_name='User ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('card', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kart No')),
                ('privilege', models.IntegerField(default=0, verbose_name='Yetki')),
                ('cihaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar', to='cardcontrol.cihaz', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Cihaz Kullanıcısı',
                'verbose_name_plural': 'Cihaz Kullanıcıları',
                'unique_together': {('cihaz', 'uid')},
            },
        ),
    ]
