# Generated by Django 5.1.6 on 2026-02-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CihazLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(verbose_name='UID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID')),
                ('timestamp', models.DateTimeField(verbose_name='Zaman')),
                ('status', models.IntegerField(default=0, verbose_name='Durum')),
                ('verification', models.IntegerField(default=0, verbose_name='Doğrulama Türü')),
                ('cihaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cardcontrol.cihaz', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Cihaz Logu',
                'verbose_name_plural': 'Cihaz Logları',
                'indexes': [models.Index(fields=['timestamp'], name='cardcontrol_timesta_a98ab2_idx'), models.Index(fields=['cihaz'], name='cardcontrol_cihaz_i_e9cd1e_idx')],
            },
        ),
    ]
