# Generated by Django 5.0.9 on 2026-04-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardcontrol', '0002_cihazlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihaz',
            name='adms_aktif',
            field=models.BooleanField(default=False, help_text='ADMS Push modu aktif mi?', verbose_name='ADMS Aktif'),
        ),
        migrations.AddField(
            model_name='cihaz',
            name='seri_no',
            field=models.CharField(blank=True, help_text='Cihazın seri numarası (ADMS Push protokolünde SN parametresi)', max_length=100, null=True, unique=True, verbose_name='Seri Numarası'),
        ),
        migrations.AddField(
            model_name='cihaz',
            name='son_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Cihazdan gelen son getrequest zamanı', null=True, verbose_name='Son Heartbeat'),
        ),
        migrations.CreateModel(
            name='ADMSKomutKuyrugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komut_id', models.PositiveIntegerField(verbose_name='Komut ID')),
                ('komut_tipi', models.CharField(max_length=50, verbose_name='Komut Tipi')),
                ('parametreler', models.TextField(blank=True, default='', verbose_name='Parametreler')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('gonderildi', models.BooleanField(default=False, verbose_name='Gönderildi')),
                ('gonderilme_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Zamanı')),
                ('cihaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komut_kuyrugu', to='cardcontrol.cihaz', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'ADMS Komut Kuyruğu',
                'verbose_name_plural': 'ADMS Komut Kuyrukları',
                'ordering': ['olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='ADMSHamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablo', models.CharField(help_text='ATTLOG, OPERLOG, USERINFO vb.', max_length=50, verbose_name='Tablo')),
                ('ham_veri', models.TextField(verbose_name='Ham Veri')),
                ('islem_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ISLENDI', 'İşlendi'), ('HATA', 'Hata')], default='BEKLEMEDE', max_length=20, verbose_name='İşlem Durumu')),
                ('hata_mesaji', models.TextField(blank=True, default='', verbose_name='Hata Mesajı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('cihaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ham_loglar', to='cardcontrol.cihaz', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'ADMS Ham Log',
                'verbose_name_plural': 'ADMS Ham Loglar',
                'ordering': ['-olusturulma'],
                'indexes': [models.Index(fields=['islem_durumu'], name='cardcontrol_islem_d_cb722d_idx'), models.Index(fields=['olusturulma'], name='cardcontrol_olustur_1b09ff_idx')],
            },
        ),
    ]
