# Generated by Django 5.0.9 on 2025-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecicigorev',
            name='gecici_gorev_tipi',
            field=models.CharField(choices=[('Gidis', 'Gidiş'), ('Gelis', 'Geliş')], default='Gidis', max_length=10),
        ),
    ]
