# Generated by Django 5.0.9 on 2025-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0002_gecicigorev_gecici_gorev_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecicigorev',
            name='asil_kurumu',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
