# Generated by Django 5.0.9 on 2025-05-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0004_ozeldurum_remove_personel_ozel_durumu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='teskilat',
            field=models.CharField(choices=[('Sözlesmeli 4B (663 sayılı KHK 45A)', 'Sözleşmeli 4B (663 sayılı KHK 45A)'), ('Döner Sermaye', 'Döner Sermaye'), ('İşçi Personel (Genel Bütçe)', 'İşçi Personel (Genel Bütçe)'), ('İşçi Personel 696 (Döner Sermaye)', 'İşçi Personel 696 (Döner Sermaye)'), ('Sözleşmeli (4924)', 'Sözleşmeli (4924)'), ('Taşra', 'Taşra')], max_length=50),
        ),
    ]
