# Generated by Django 5.0.9 on 2025-06-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0005_alter_personel_teskilat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='adres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='aile_hek_sozlesmesi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='atama_karar_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='ayrilma_detay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='ayrilma_nedeni',
            field=models.CharField(blank=True, choices=[('Emeklilik', 'Emeklilik'), ('Tayin', 'Tayin'), ('TUS', 'TUS'), ('Diger', 'Diğer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadin', 'Kadın')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='emekli_sicil_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='engel_orani',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='eposta',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='kadrolu_personel',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='mazeret_durumu',
            field=models.CharField(blank=True, choices=[('Saglik', 'Sağlık'), ('Egitim', 'Eğitim'), ('EsDurumu', 'Eş Durumu'), ('AileBirligiDagilmasi', 'Aile Birliğinin Dağılması')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='memur_devreden_izin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='memur_hak_ettigi_izin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='ozel_durumu_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='sicil_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='tahsil_durumu',
            field=models.CharField(blank=True, choices=[('Okuryazar', 'Okuryazar'), ('İlkokul', 'İlkokul'), ('Ortaokul', 'Ortaokul'), ('İlköğretim', 'İlköğretim'), ('Lise', 'Lise'), ('Önlisans', 'Önlisans'), ('Lisans', 'Lisans'), ('Yük. Öğr.(5 Yıl)', 'Yük. Öğr.(5 Yıl)'), ('Lisans Sonrası 1 Yıl', 'Lisans Sonrası 1 Yıl'), ('Yüksek Lisans', 'Yüksek Lisans'), ('Diş Hekimliği', 'Diş Hekimliği'), ('Tıp Fakültesi', 'Tıp Fakültesi'), ('Tıpta Uzmanlık', 'Tıpta Uzmanlık')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='telefon',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='teskilat',
            field=models.CharField(blank=True, choices=[('Sözlesmeli 4B (663 sayılı KHK 45A)', 'Sözleşmeli 4B (663 sayılı KHK 45A)'), ('Döner Sermaye', 'Döner Sermaye'), ('İşçi Personel (Genel Bütçe)', 'İşçi Personel (Genel Bütçe)'), ('İşçi Personel 696 (Döner Sermaye)', 'İşçi Personel 696 (Döner Sermaye)'), ('Sözleşmeli (4924)', 'Sözleşmeli (4924)'), ('Taşra', 'Taşra')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='vergi_indirimi',
            field=models.CharField(blank=True, choices=[('1.Derece Engelli (%80 ve üzeri)', '1.Derece Engelli (%80 ve üzeri)'), ('2.Derece Engelli (%60-79)', '2.Derece Engelli (%60-79)'), ('3.Derece Engelli (%40-59)', '3.Derece Engelli (%40-59)')], max_length=31, null=True),
        ),
    ]
