# Generated by Django 5.0.9 on 2025-10-06 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0006_alter_personel_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='kayit_tarihi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
