# Generated by Django 5.0.9 on 2025-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0007_personel_kayit_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='aday_memur',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
