# Generated by Django 5.1.6 on 2025-10-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0009_alter_personel_teskilat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TebligImzasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('metin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TebligMetni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('metin', models.TextField()),
            ],
        ),
    ]
