# Generated by Django 5.1.6 on 2025-10-21 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0010_tebligimzasi_tebligmetni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Bina Adı')),
            ],
            options={
                'verbose_name': 'Bina',
                'verbose_name_plural': 'Binalar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='UstBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Üst Birim Adı')),
            ],
            options={
                'verbose_name': 'Üst Birim',
                'verbose_name_plural': 'Üst Birimler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Birim Adı')),
                ('bina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.bina', verbose_name='Bina')),
                ('ust_birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.ustbirim', verbose_name='Üst Birim')),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
                'ordering': ['ust_birim__ad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='PersonelBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gecis_tarihi', models.DateField(verbose_name='Geçiş Tarihi')),
                ('sorumlu', models.BooleanField(default=False, verbose_name='Sorumlu')),
                ('not_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Not')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.birim', verbose_name='Birim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Personel Birim',
                'verbose_name_plural': 'Personel Birimler',
                'ordering': ['-gecis_tarihi', '-creation_timestamp'],
            },
        ),
    ]
