# Generated by Django 5.0.9 on 2025-10-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0011_bina_ustbirim_birim_personelbirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResmiYazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('metin', models.TextField()),
            ],
        ),
    ]
