# Generated by Django 5.0.9 on 2025-10-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0012_resmiyazi'),
    ]

    operations = [
        migrations.AddField(
            model_name='resmiyazi',
            name='ek',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resmiyazi',
            name='ilgi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
