# Generated by Django 5.0.9 on 2025-12-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0013_resmiyazi_ek_resmiyazi_ilgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KisaUnvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kısa Ünvan / Grup')),
                ('ust_birim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik_core.ustbirim', verbose_name='Bağlı Olduğu Üst Birim')),
            ],
            options={
                'verbose_name': 'Kısa Ünvan',
                'verbose_name_plural': 'Kısa Ünvanlar',
            },
        ),
        migrations.CreateModel(
            name='UnvanBransEslestirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik_core.brans')),
                ('kisa_unvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.kisaunvan', verbose_name='Kısa Ünvan')),
                ('unvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.unvan')),
            ],
            options={
                'verbose_name': 'Ünvan Branş Eşleştirme',
                'verbose_name_plural': 'Ünvan Branş Eşleştirmeleri',
                'unique_together': {('unvan', 'brans')},
            },
        ),
        migrations.AddField(
            model_name='personel',
            name='unvan_brans_eslestirme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ik_core.unvanbranseslestirme', verbose_name='Ünvan Branş Eşleştirme'),
        ),
    ]
