# Generated by Django 5.1.6 on 2025-12-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0014_kisaunvan_unvanbranseslestirme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birim',
            name='birim_tipi',
            field=models.CharField(default=0, max_length=50, verbose_name='Birim Tipi'),
            preserve_default=False,
        ),
    ]
