# Generated by Django 5.1.6 on 2025-12-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0015_birim_birim_tipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurumBelgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('metin', models.TextField()),
            ],
        ),
    ]
