# Generated by Django 5.0.9 on 2026-01-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0016_durumbelgesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kampüs Adı')),
                ('gorsel', models.ImageField(upload_to='kampus_krokileri/', verbose_name='Kampüs Krokisi/Render')),
            ],
            options={
                'verbose_name': 'Kampüs',
                'verbose_name_plural': 'Kampüsler',
            },
        ),
        migrations.AddField(
            model_name='bina',
            name='aciklama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Açıklama (Örn: 3 Katlı)'),
        ),
        migrations.AddField(
            model_name='bina',
            name='koordinatlar',
            field=models.TextField(blank=True, help_text='SVG Polygon noktaları (x1,y1 x2,y2...)', null=True),
        ),
        migrations.AddField(
            model_name='bina',
            name='kampus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binalar', to='ik_core.kampus', verbose_name='Kampüs'),
        ),
    ]
