# Generated by Django 5.1.6 on 2026-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0017_kampus_bina_aciklama_bina_koordinatlar_bina_kampus'),
    ]

    operations = [
        migrations.AddField(
            model_name='birim',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
