# Generated by Django 5.1.6 on 2026-03-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0018_birim_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertifika_aciklamasi', models.TextField(verbose_name='Sertifika Açıklaması')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('alanda_kullaniliyor', models.BooleanField(default=False, verbose_name='Alanda Kullanılıyor')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikalar', to='ik_core.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
            },
        ),
    ]
