# Generated by Django 5.1.6 on 2025-07-18 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NobetTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NobetDefteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('vardiya', models.CharField(choices=[('Gündüz', 'Gündüz'), ('Akşam', 'Akşam'), ('Gece', 'Gece')], max_length=10)),
                ('aciklama', models.TextField(blank=True)),
                ('onayli', models.BooleanField(default=False)),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nobet_defterleri_olusturan', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('onaylayan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nobet_defterleri_onaylayan', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('nobet_turu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobet_defteri.nobetturu')),
            ],
            options={
                'unique_together': {('tarih', 'nobet_turu', 'vardiya')},
            },
        ),
        migrations.CreateModel(
            name='NobetOlayKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.TimeField()),
                ('konu', models.CharField(max_length=200)),
                ('detay', models.TextField()),
                ('eklenme_zamani', models.DateTimeField(auto_now_add=True)),
                ('defter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olaylar', to='nobet_defteri.nobetdefteri')),
                ('ekleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
