# Generated by Django 5.0.9 on 2025-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobet_defteri', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nobetdefteri',
            unique_together={('tarih', 'nobet_turu')},
        ),
        migrations.AddField(
            model_name='nobetolaykaydi',
            name='onemli',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='nobetdefteri',
            name='vardiya',
        ),
    ]
