# Generated by Django 5.1.6 on 2025-08-27 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobet_defteri', '0002_alter_nobetdefteri_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KontrolSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.CharField(max_length=255)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KontrolFormu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('nobet_defteri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kontrol_formu', to='nobet_defteri.nobetdefteri')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KontrolCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap', models.BooleanField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='nobet_defteri.kontrolformu')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nobet_defteri.kontrolsoru')),
            ],
        ),
    ]
