# Generated by Django 5.0.9 on 2025-09-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobet_defteri', '0003_kontrolsoru_kontrolformu_kontrolcevap'),
    ]

    operations = [
        migrations.CreateModel(
            name='NobetciTekniker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekniker_adi', models.CharField(max_length=100)),
                ('gelis_saati', models.TimeField()),
                ('ayrilis_saati', models.TimeField()),
                ('defter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teknikerler', to='nobet_defteri.nobetdefteri')),
            ],
            options={
                'unique_together': {('defter', 'tekniker_adi')},
            },
        ),
    ]
