# Generated by Django 5.0.3 on 2025-04-12 17:22

import django.db.models.deletion
import mutemet_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendikaUyelik',
            fields=[
                ('uyelik_id', models.AutoField(primary_key=True, serialize=False)),
                ('hareket_tipi', models.CharField(choices=[('UYELIK', 'Üyelik'), ('AYRILMA', 'Ayrılma')], max_length=10)),
                ('hareket_tarihi', models.DateField()),
                ('maas_donemi', models.DateField()),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncellenen_sendika_hareketleri', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_sendika_hareketleri', to=settings.AUTH_USER_MODEL)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendika_hareketleri', to='mutemet_app_personel')),
                ('sendika_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendika_uyelik_hareketleri', to='mutemet_app_sendika')),
            ],
            options={
                'verbose_name': 'Sendika Üyelik Hareketi',
                'verbose_name_plural': 'Sendika Üyelik Hareketleri',
                'ordering': ['-hareket_tarihi'],
            },
        ),
    ]
