# Generated by Django 5.0.3 on 2025-04-12 17:29

import django.db.models.deletion
import mutemet_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutemet_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('personel_id', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[mutemet_app.models.validate_tc_kimlik_no])),
                ('sicil_no', models.CharField(max_length=20)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('unvan', models.CharField(max_length=100)),
                ('brans', models.CharField(max_length=100)),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif'), ('AYRILDI', 'Kurumdan Ayrıldı')], default='AKTIF', max_length=10)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelleyen_personeller', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturan_personeller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'ordering': ['ad', 'soyad'],
            },
        ),
        migrations.CreateModel(
            name='OdemeTakibi',
            fields=[
                ('odeme_id', models.AutoField(primary_key=True, serialize=False)),
                ('odeme_tipi', models.CharField(choices=[('MAAS', 'Maaş'), ('AVANS', 'Avans'), ('IKRAMIYE', 'İkramiye'), ('DIGER', 'Diğer')], max_length=10)),
                ('odeme_tarihi', models.DateField()),
                ('odeme_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelleyen_odemeler', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturan_odemeler', to=settings.AUTH_USER_MODEL)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutemet_app.personel')),
            ],
            options={
                'verbose_name': 'Ödeme Takibi',
                'verbose_name_plural': 'Ödeme Takipleri',
                'ordering': ['-odeme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='IcraTakibi',
            fields=[
                ('icra_id', models.AutoField(primary_key=True, serialize=False)),
                ('icra_no', models.CharField(max_length=50)),
                ('icra_tarihi', models.DateField()),
                ('icra_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif'), ('KAPANDI', 'Kapandı')], default='AKTIF', max_length=10)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelleyen_icralar', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturan_icralar', to=settings.AUTH_USER_MODEL)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutemet_app.personel')),
            ],
            options={
                'verbose_name': 'İcra Takibi',
                'verbose_name_plural': 'İcra Takipleri',
                'ordering': ['-icra_tarihi'],
            },
        ),
        migrations.AlterField(
            model_name='sendikauyelik',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendika_hareketleri', to='mutemet_app.personel'),
        ),
        migrations.CreateModel(
            name='PersonelHareket',
            fields=[
                ('hareket_id', models.AutoField(primary_key=True, serialize=False)),
                ('hareket_tipi', models.CharField(choices=[('BASLAMA', 'Başlama'), ('IZIN', 'Ücretsiz İzin'), ('DONUS', 'İzin Dönüşü'), ('AYRILMA', 'Ayrılma')], max_length=10)),
                ('hareket_tarihi', models.DateField()),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelleyen_personel_hareketleri', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturan_personel_hareketleri', to=settings.AUTH_USER_MODEL)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutemet_app.personel')),
            ],
            options={
                'verbose_name': 'Personel Hareketi',
                'verbose_name_plural': 'Personel Hareketleri',
                'ordering': ['-hareket_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Sendika',
            fields=[
                ('sendika_id', models.AutoField(primary_key=True, serialize=False)),
                ('sendika_adi', models.CharField(max_length=100)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelleyen_sendikalar', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturan_sendikalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sendika',
                'verbose_name_plural': 'Sendikalar',
                'ordering': ['sendika_adi'],
            },
        ),
        migrations.AlterField(
            model_name='sendikauyelik',
            name='sendika_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendika_uyelik_hareketleri', to='mutemet_app.sendika'),
        ),
    ]
