# Generated by Django 5.0.9 on 2025-04-13 18:41

import django.db.models.deletion
from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('mutemet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icratakibi',
            options={'ordering': ['-tarihi'], 'verbose_name': 'İcra Takibi', 'verbose_name_plural': 'İcra Takipleri'},
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='guncelleme_tarihi',
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='guncelleyen',
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='icra_no',
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='icra_tarihi',
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='icra_tutari',
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='olusturan',
        ),
        migrations.RemoveField(
            model_name='icratakibi',
            name='olusturma_tarihi',
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='alacakli',
            field=models.CharField(default=1, max_length=100, verbose_name='Alacaklı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='alacakli_vekili',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alacaklı Vekili'),
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='dosya_no',
            field=models.CharField(default=1, max_length=50, verbose_name='Dosya No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='icra_dairesi',
            field=models.CharField(default=1, max_length=100, verbose_name='İcra Dairesi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='icra_dairesi_banka',
            field=models.CharField(default=1, max_length=100, verbose_name='Banka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='icra_dairesi_hesap_no',
            field=models.CharField(default=1, max_length=50, verbose_name='Hesap No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='icra_vergi_dairesi_no',
            field=models.CharField(default=1, max_length=50, verbose_name='Vergi Dairesi No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='tarihi',
            field=models.DateField(default=date.today, verbose_name='İcra Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icratakibi',
            name='tutar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Tutar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icratakibi',
            name='durum',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif'), ('KAPANDI', 'Kapandı')], default='AKTIF', max_length=10, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='IcraHareketleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesilen_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kesilen Tutar')),
                ('kesildigi_donem', models.DateField(verbose_name='Kesildiği Dönem')),
                ('odeme_turu', models.CharField(choices=[('DENGE', 'Denge'), ('DENGE FARK', 'Denge Fark'), ('EK ÖDEME', 'Ek Ödeme'), ('ELDEN', 'Elden'), ('İKRAMİYE', 'İkramiye'), ('MAAŞ', 'Maaş'), ('NAFAKA', 'Nafaka'), ('SABİT', 'Sabit'), ('SABİT FARK', 'Sabit Fark'), ('TEMEL', 'Temel'), ('TEŞVİK', 'Teşvik'), ('TOPLU GİRİŞ', 'Toplu Giriş')], max_length=20, verbose_name='Ödeme Türü')),
                ('icra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icrahareketleri_set', to='mutemet_app.icratakibi')),
            ],
            options={
                'verbose_name': 'İcra Hareketi',
                'verbose_name_plural': 'İcra Hareketleri',
                'ordering': ['-kesildigi_donem'],
            },
        ),
    ]
