# Generated by Django 5.1.6 on 2025-05-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ik_core', '0004_ozeldurum_remove_personel_ozel_durumu_and_more'),
        ('mutemet_app', '0002_alter_icratakibi_options_remove_icratakibi_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendikauyelik',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendika_hareketleri', to='ik_core.personel'),
        ),
        migrations.AlterField(
            model_name='odemetakibi',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.personel'),
        ),
        migrations.AlterField(
            model_name='personelhareket',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.personel'),
        ),
        migrations.AlterField(
            model_name='icratakibi',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ik_core.personel'),
        ),
        migrations.DeleteModel(
            name='Personel',
        ),
    ]
