# Generated by Django 5.0.9 on 2025-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutemet_app', '0003_alter_sendikauyelik_personel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icratakibi',
            name='icra_turu',
            field=models.CharField(choices=[('NAFAKA', 'Nafaka'), ('TAAHHUT', 'Taahhüt'), ('ICRA', 'İcra')], default='ICRA', max_length=10, verbose_name='İcra Türü'),
        ),
        migrations.AlterField(
            model_name='icratakibi',
            name='durum',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('SIRADA', 'Sırada'), ('KAPANDI', 'Kapandı')], default='AKTIF', max_length=10, verbose_name='Durum'),
        ),
    ]
