# Generated by Django 5.1.6 on 2025-04-17 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet_sunum_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkili_kullanicilar', to='hizmet_sunum_app.birim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkili_oldugu_birimler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Birim Yetkisi',
                'verbose_name_plural': 'Kullanıcı Birim Yetkileri',
                'unique_together': {('user', 'birim')},
            },
        ),
    ]
