# Generated by Django 5.1.6 on 2025-04-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet_sunum_app', '0002_userbirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='TCKimlikNo',
            field=models.CharField(default=12345678910, max_length=11, unique=True, verbose_name='T.C. Kimlik No'),
            preserve_default=False,
        ),
    ]
