# Generated by Django 5.1.6 on 2025-04-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet_sunum_app', '0003_personel_tckimlikno'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetsunumcalismasi',
            name='OzelAlanKodu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Özel Alan Kodu'),
        ),
    ]
