# Generated by Django 5.0.9 on 2025-06-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet_sunum_app', '0004_hizmetsunumcalismasi_ozelalankodu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbirim',
            name='birim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizmet_sunum_kullanicilari', to='hizmet_sunum_app.birim'),
        ),
        migrations.AlterField(
            model_name='userbirim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizmet_sunum_birimleri', to=settings.AUTH_USER_MODEL),
        ),
    ]
