# Generated by Django 5.1.6 on 2025-06-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet_sunum_app', '0005_alter_userbirim_birim_alter_userbirim_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetsunumalani',
            name='SorumluAtanabilir',
            field=models.BooleanField(default=False, verbose_name='Sorumlu Atanabilir'),
        ),
    ]
