# Generated by Django 5.0.9 on 2025-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet_sunum_app', '0006_hizmetsunumalani_sorumluatanabilir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='birim',
            name='IdareAdi',
            field=models.CharField(max_length=50, null=True, verbose_name='İdare Adı'),
        ),
    ]
