"""
Django settings for PersonelYonSis project.

Generated by 'django-admin startproject' using Django 5.1.1.

"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x*7co6u42+!g_%i^@pk)4k2(^iobt8qixcpc8f35&$(5wxw9q8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.38.12.55', '10.38.12.59', '127.0.0.1', 'localhost']  # Geliştirme aşamasında localhost

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Sayı formatlaması için
    'crispy_forms',
    'crispy_bootstrap5',
    'mercis657',
    'PersonelYonSis',
    'hekim_cizelge',
    'mutemet_app',
    'hizmet_sunum_app',
    'ik_core',
    'nobet_defteri',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'PersonelYonSis.middleware.LoginRequiredMiddleware',# Kendi oluşturduğumuz Login gerektirme dosyası
]

ROOT_URLCONF = 'PersonelYonSis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'PersonelYonSis.context_processors.menu_processor',# Eklediğimiz processor menü yetkilendirmeleri için
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PersonelYonSis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Veritabanı dosyasının yolu
    }
}


#Djangonunki yerine Kendi user modelimizi kullanacağız
AUTH_USER_MODEL = 'PersonelYonSis.User'
AUTHENTICATION_BACKENDS = ['PersonelYonSis.backends.CustomUserBackend']

LOGIN_URL = '/login/'  # Giriş yapılmadığında yönlendirilecek URL


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# API Configuration
API_AUTH_KEY = "sacid_010101" 

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Dil ayarı Türkçe olarak değiştiriliyor
LANGUAGE_CODE = 'tr'

# Zaman dilimi Türkiye olarak ayarlanıyor
TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Statik dosyalarınızın bulunduğu klasör
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
