from .main_views import *
from .vardiya_dagilim_views import *
from .cizelge_edit_views import *
from .birim_views import *
from .personel_views import *
from .izin_views import *
from .mesai_views import *
from .mazeret_views import *
from .personel_islem_views import *
from .bildirim_views import *
from .tanimlamalar_views import *
from .raporlama_views import *
from .yonetici_views import *
from .stop_views import *
from .ilk_liste_views import *
from .imza_cizelgeleri_views import *