from .main_views import *
from .cizelge_edit_views import *
from .birim_views import *
from .personel_views import *
from .izin_views import *
from .mesai_views import *
from .mazeret_views import *
from .personel_islem_views import *
from .bildirim_views import *
from .tanimlamalar_views import *